"""Alembic environment.

The connection URL always comes from application configuration, so migrations
run against exactly the database the service uses and no credential is stored
in a committed file.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from qguard.common.config import get_settings
from qguard.models import Base
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata
settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.sync_database_url)


def include_object(obj, name, type_, reflected, compare_to):
    """Keep Supabase's own managed schemas out of autogenerated diffs."""
    managed_schemas = {
        "auth",
        "storage",
        "realtime",
        "extensions",
        "graphql",
        "vault",
        "supabase_functions",
        "_realtime",
    }
    return not (type_ == "table" and getattr(obj, "schema", None) in managed_schemas)


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
            include_object=include_object,
            transaction_per_migration=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
